name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: AutoMerge Dependabot PRs
      if: success() && github.actor == 'dependabot[bot]' && github.ref != 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        echo "found successful dependabot PR, merging it"
        gh pr merge --auto --merge
